# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Photo library
  pod 'YPImagePicker'

  use_frameworks!

  # Pods for Photo_tutorial

end
